# Generated by Django 5.0.5 on 2024-05-16 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EyeHealth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type_of_training',
            new_name='Type_of_warm_up',
        ),
        migrations.RemoveField(
            model_name='difficulty_level',
            name='type_of_training',
        ),
        migrations.RemoveField(
            model_name='result',
            name='type_of_training',
        ),
        migrations.AddField(
            model_name='difficulty_level',
            name='type_of_warm_up',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='EyeHealth.type_of_warm_up', verbose_name='Тип разминки'),
        ),
        migrations.AddField(
            model_name='result',
            name='allClickCount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Общее количество необходимых кликов'),
        ),
        migrations.AddField(
            model_name='result',
            name='task_block',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EyeHealth.task_block', verbose_name='Тест'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='usersClickCount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество верных кликов пользователя'),
        ),
        migrations.AddField(
            model_name='task_block',
            name='is_active_block',
            field=models.BooleanField(default=False, verbose_name='Активный блок'),
        ),
        migrations.AlterField(
            model_name='result',
            name='correct',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кол-во правильных ответов'),
        ),
        migrations.AlterField(
            model_name='result',
            name='wrong',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кол-во неправильных ответов'),
        ),
    ]
