# Generated by Django 5.0.5 on 2024-05-16 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EyeHealth', '0002_rename_type_of_training_type_of_warm_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty_level',
            name='type_of_warm_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EyeHealth.type_of_warm_up', verbose_name='Тип разминки'),
        ),
    ]
