# Generated by Django 5.0.5 on 2024-05-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EyeHealth', '0003_alter_difficulty_level_type_of_warm_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_of_warm_up',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Название'),
        ),
    ]
