# Generated by Django 5.0.5 on 2024-05-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EyeHealth', '0004_alter_type_of_warm_up_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty_level',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Сложность'),
        ),
    ]
