# Generated by Django 5.0.5 on 2024-05-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EyeHealth', '0005_alter_difficulty_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.TextField(verbose_name='Правильный ответ'),
        ),
    ]
