# Generated by Django 5.0.5 on 2024-05-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EyeHealth', '0008_alter_choice_user_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EyeHealth.task_block', verbose_name='Тест')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='users_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='EyeHealth.users_block'),
        ),
    ]
