# Generated by Django 5.0.5 on 2024-05-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EyeHealth', '0010_remove_task_block_is_active_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answered',
        ),
    ]
